import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class DataService {
  private data: any[] = [
    {
      id: '#ERTY567890',
      payment_type: 'Card',
      amount: 'N45,050.00',
      date: '23 Aug, 2023',
      description: 'Random Text',
      status: 'Completed',
    },
    {
      id: '#KLMN123456',
      payment_type: 'Transfer',
      amount: 'N63,280.50',
      date: '15 Nov, 2023',
      description: 'Random Text',
      status: 'Completed',
    },
    {
      id: '#ABCD987654',
      payment_type: 'Cash',
      amount: 'N22,750.75',
      date: '07 May, 2023',
      description: 'Random Text',
      status: 'Failed',
    },
    {
      id: '#PQRS345678',
      payment_type: 'Card',
      amount: 'N81,493.30',
      date: '19 Jul, 2023',
      description: 'Random Text',
      status: 'Pending',
    },
    {
      id: '#WXYZ789012',
      payment_type: 'Cash',
      amount: 'N75,625.20',
      date: '09 Sep, 2023',
      description: 'Random Text',
      status: 'Completed',
    },
    {
      id: '#EFGH234567',
      payment_type: 'Transfer',
      amount: 'N5,678.90',
      date: '31 Dec, 2023',
      description: 'Random Text',
      status: 'Failed',
    },
    {
      id: '#IJKL456789',
      payment_type: 'Transfer',
      amount: 'N98,123.45',
      date: '13 Feb, 2023',
      description: 'Random Text',
      status: 'Completed',
    },
    {
      id: '#UVWX567890',
      payment_type: 'Cash',
      amount: 'N12,345.60',
      date: '28 Oct, 2023',
      description: 'Random Text',
      status: 'Pending',
    },
    {
      id: '#MNOP678901',
      payment_type: 'Card',
      amount: 'N42,567.80',
      date: '05 Apr, 2023',
      description: 'Random Text',
      status: 'Failed',
    },
    {
      id: '#QRST789012',
      payment_type: 'Cash',
      amount: 'N36,789.10',
      date: '11 Jun, 2023',
      description: 'Random Text',
      status: 'Completed',
    },
    {
      id: '#VWXY890123',
      payment_type: 'Transfer',
      amount: 'N72,901.20',
      date: '25 Aug, 2023',
      description: 'Random Text',
      status: 'Pending',
    },
    {
      id: '#LMNO901234',
      payment_type: 'Cash',
      amount: 'N88,012.30',
      date: '02 Mar, 2023',
      description: 'Random Text',
      status: 'Completed',
    },
    {
      id: '#FGHI012345',
      payment_type: 'Card',
      amount: 'N9,876.40',
      date: '16 Sep, 2023',
      description: 'Random Text',
      status: 'Failed',
    },
    {
      id: '#TUVW123456',
      payment_type: 'Card',
      amount: 'N31,234.50',
      date: '20 Dec, 2023',
      description: 'Random Text',
      status: 'Pending',
    },
    {
      id: '#OPQR234567',
      payment_type: 'Cash',
      amount: 'N54,321.60',
      date: '06 Feb, 2023',
      description: 'Random Text',
      status: 'Completed',
    },
    {
      id: '#XYZ567890',
      payment_type: 'Transfer',
      amount: 'N47,890.70',
      date: '22 Jul, 2023',
      description: 'Random Text',
      status: 'Pending',
    },
    {
      id: '#CDEF678901',
      payment_type: 'Cash',
      amount: 'N68,901.80',
      date: '04 Nov, 2023',
      description: 'Random Text',
      status: 'Failed',
    },
    {
      id: '#HIJK789012',
      payment_type: 'Transfer',
      amount: 'N23,012.90',
      date: '18 Jan, 2023',
      description: 'Random Text',
      status: 'Completed',
    },
    {
      id: '#RSTU890123',
      payment_type: 'Card',
      amount: 'N78,901.00',
      date: '09 May, 2023',
      description: 'Random Text',
      status: 'Failed',
    },
    {
      id: '#VWXYZ901234',
      payment_type: 'Cash',
      amount: 'N14,321.10',
      date: '27 Jul, 2023',
      description: 'Random Text',
      status: 'Completed',
    },
    {
      id: '#GHIJ012345',
      payment_type: 'Transfer',
      amount: 'N60,123.20',
      date: '14 Sep, 2023',
      description: 'Random Text',
      status: 'Pending',
    },
    {
      id: '#QRST123456',
      payment_type: 'Card',
      amount: 'N44,321.30',
      date: '08 Dec, 2023',
      description: 'Random Text',
      status: 'Failed',
    },
    {
      id: '#UVWX234567',
      payment_type: 'Cash',
      amount: 'N33,456.40',
      date: '26 Feb, 2023',
      description: 'Random Text',
      status: 'Completed',
    },
    {
      id: '#MNOP345678',
      payment_type: 'Transfer',
      amount: 'N29,012.50',
      date: '02 Apr, 2023',
      description: 'Random Text',
      status: 'Pending',
    },
    {
      id: '#ABCD456789',
      payment_type: 'Transfer',
      amount: 'N66,543.60',
      date: '17 Aug, 2023',
      description: 'Random Text',
      status: 'Completed',
    },
    {
      id: '#EFGH567890',
      payment_type: 'Cash',
      amount: 'N11,234.70',
      date: '03 Oct, 2023',
      description: 'Random Text',
      status: 'Pending',
    },
    {
      id: '#IJKL678901',
      payment_type: 'Card',
      amount: 'N55,432.80',
      date: '21 Feb, 2023',
      description: 'Random Text',
      status: 'Failed',
    },
    {
      id: '#UVWX789012',
      payment_type: 'Cash',
      amount: 'N40,123.90',
      date: '12 Jun, 2023',
      description: 'Random Text',
      status: 'Completed',
    },
    {
      id: '#OPQR890123',
      payment_type: 'Card',
      amount: 'N70,987.00',
      date: '24 Aug, 2023',
      description: 'Random Text',
      status: 'Failed',
    },
    {
      id: '#TUVW901234',
      payment_type: 'Transfer',
      amount: 'N17,890.10',
      date: '10 Jan, 2023',
      description: 'Random Text',
      status: 'Pending',
    },
    {
      id: '#LMNO012345',
      payment_type: 'Cash',
      amount: 'N25,432.20',
      date: '29 Apr, 2023',
      description: 'Random Text',
      status: 'Completed',
    },
    {
      id: '#QRST123456',
      payment_type: 'Card',
      amount: 'N64,321.30',
      date: '05 Dec, 2023',
      description: 'Random Text',
      status: 'Failed',
    },
    {
      id: '#VWXYZ234567',
      payment_type: 'Cash',
      amount: 'N38,765.40',
      date: '19 Feb, 2023',
      description: 'Random Text',
      status: 'Completed',
    },
    {
      id: '#CDEF345678',
      payment_type: 'Transfer',
      amount: 'N47,890.50',
      date: '27 Jun, 2023',
      description: 'Random Text',
      status: 'Pending',
    },
    {
      id: '#HIJK456789',
      payment_type: 'Transfer',
      amount: 'N30,123.60',
      date: '15 Oct, 2023',
      description: 'Random Text',
      status: 'Completed',
    },
    {
      id: '#RSTU567890',
      payment_type: 'Card',
      amount: 'N21,234.70',
      date: '09 Mar, 2023',
      description: 'Random Text',
      status: 'Failed',
    },
    {
      id: '#VWXYZ678901',
      payment_type: 'Cash',
      amount: 'N15,432.80',
      date: '23 Sep, 2023',
      description: 'Random Text',
      status: 'Completed',
    },
  ];

  constructor() {}

  getData(): Observable<any[]> {
    return of(this.data);
  }
}
