import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class DataService {
  private data: any[] = [
    {
      id: '#AD45/R5-CL',
      Customer: 'Sharafadeen Musa',
      payment_type: 'Card',
      amount: 'N3,000',
      date: '23 Aug, 2023',
      status: 'Pending',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Brenda Tony',
      payment_type: 'Transfer',
      amount: 'N4,500',
      date: '23 Aug, 2023',
      status: 'Delivered',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Sharafadeen Musa',
      payment_type: 'Card',
      amount: 'N5,000',
      date: '23 Aug, 2023',
      status: 'Ready',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Sharafadeen Musa',
      payment_type: 'Card',
      amount: 'N3,000',
      date: '23 Aug, 2023',
      status: 'Pending',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Brenda Tony',
      payment_type: 'Transfer',
      amount: 'N4,500',
      date: '23 Aug, 2023',
      status: 'Delivered',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Sharafadeen Musa',
      payment_type: 'Card',
      amount: 'N5,000',
      date: '23 Aug, 2023',
      status: 'Ready',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Sharafadeen Musa',
      payment_type: 'Card',
      amount: 'N3,000',
      date: '23 Aug, 2023',
      status: 'Pending',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Brenda Tony',
      payment_type: 'Transfer',
      amount: 'N4,500',
      date: '23 Aug, 2023',
      status: 'Delivered',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Sharafadeen Musa',
      payment_type: 'Card',
      amount: 'N5,000',
      date: '23 Aug, 2023',
      status: 'Ready',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Sharafadeen Musa',
      payment_type: 'Card',
      amount: 'N3,000',
      date: '23 Aug, 2023',
      status: 'Pending',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Brenda Tony',
      payment_type: 'Transfer',
      amount: 'N4,500',
      date: '23 Aug, 2023',
      status: 'Delivered',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Sharafadeen Musa',
      payment_type: 'Card',
      amount: 'N5,000',
      date: '23 Aug, 2023',
      status: 'Ready',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Sharafadeen Musa',
      payment_type: 'Card',
      amount: 'N3,000',
      date: '23 Aug, 2023',
      status: 'Pending',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Brenda Tony',
      payment_type: 'Transfer',
      amount: 'N4,500',
      date: '23 Aug, 2023',
      status: 'Delivered',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Sharafadeen Musa',
      payment_type: 'Card',
      amount: 'N5,000',
      date: '23 Aug, 2023',
      status: 'Ready',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Sharafadeen Musa',
      payment_type: 'Card',
      amount: 'N3,000',
      date: '23 Aug, 2023',
      status: 'Pending',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Brenda Tony',
      payment_type: 'Transfer',
      amount: 'N4,500',
      date: '23 Aug, 2023',
      status: 'Delivered',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Sharafadeen Musa',
      payment_type: 'Card',
      amount: 'N5,000',
      date: '23 Aug, 2023',
      status: 'Ready',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Sharafadeen Musa',
      payment_type: 'Card',
      amount: 'N3,000',
      date: '23 Aug, 2023',
      status: 'Pending',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Brenda Tony',
      payment_type: 'Transfer',
      amount: 'N4,500',
      date: '23 Aug, 2023',
      status: 'Delivered',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Sharafadeen Musa',
      payment_type: 'Card',
      amount: 'N5,000',
      date: '23 Aug, 2023',
      status: 'Ready',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Sharafadeen Musa',
      payment_type: 'Card',
      amount: 'N3,000',
      date: '23 Aug, 2023',
      status: 'Pending',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Brenda Tony',
      payment_type: 'Transfer',
      amount: 'N4,500',
      date: '23 Aug, 2023',
      status: 'Delivered',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Sharafadeen Musa',
      payment_type: 'Card',
      amount: 'N5,000',
      date: '23 Aug, 2023',
      status: 'Ready',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Sharafadeen Musa',
      payment_type: 'Card',
      amount: 'N3,000',
      date: '23 Aug, 2023',
      status: 'Pending',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Brenda Tony',
      payment_type: 'Transfer',
      amount: 'N4,500',
      date: '23 Aug, 2023',
      status: 'Delivered',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Sharafadeen Musa',
      payment_type: 'Card',
      amount: 'N5,000',
      date: '23 Aug, 2023',
      status: 'Ready',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Sharafadeen Musa',
      payment_type: 'Card',
      amount: 'N3,000',
      date: '23 Aug, 2023',
      status: 'Pending',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Brenda Tony',
      payment_type: 'Transfer',
      amount: 'N4,500',
      date: '23 Aug, 2023',
      status: 'Delivered',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Sharafadeen Musa',
      payment_type: 'Card',
      amount: 'N5,000',
      date: '23 Aug, 2023',
      status: 'Ready',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Sharafadeen Musa',
      payment_type: 'Card',
      amount: 'N3,000',
      date: '23 Aug, 2023',
      status: 'Pending',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Brenda Tony',
      payment_type: 'Transfer',
      amount: 'N4,500',
      date: '23 Aug, 2023',
      status: 'Delivered',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Sharafadeen Musa',
      payment_type: 'Card',
      amount: 'N5,000',
      date: '23 Aug, 2023',
      status: 'Ready',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Sharafadeen Musa',
      payment_type: 'Card',
      amount: 'N3,000',
      date: '23 Aug, 2023',
      status: 'Pending',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Brenda Tony',
      payment_type: 'Transfer',
      amount: 'N4,500',
      date: '23 Aug, 2023',
      status: 'Delivered',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Sharafadeen Musa',
      payment_type: 'Card',
      amount: 'N5,000',
      date: '23 Aug, 2023',
      status: 'Ready',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Sharafadeen Musa',
      payment_type: 'Card',
      amount: 'N3,000',
      date: '23 Aug, 2023',
      status: 'Pending',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Brenda Tony',
      payment_type: 'Transfer',
      amount: 'N4,500',
      date: '23 Aug, 2023',
      status: 'Delivered',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Sharafadeen Musa',
      payment_type: 'Card',
      amount: 'N5,000',
      date: '23 Aug, 2023',
      status: 'Ready',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Sharafadeen Musa',
      payment_type: 'Card',
      amount: 'N3,000',
      date: '23 Aug, 2023',
      status: 'Pending',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Brenda Tony',
      payment_type: 'Transfer',
      amount: 'N4,500',
      date: '23 Aug, 2023',
      status: 'Delivered',
    },
    {
      id: '#AD45/R5-CL',
      Customer: 'Sharafadeen Musa',
      payment_type: 'Card',
      amount: 'N5,000',
      date: '23 Aug, 2023',
      status: 'Ready',
    },


  ];

  constructor() {}

  getData(): Observable<any[]> {
    return of(this.data);
  }
}
